<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Complaint;
use Illuminate\Database\Seeder;

class ComplaintSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::query()
            ->whereIn('name', [
                'Sarana dan Prasarana Kampus',
                'Kebersihan dan Sanitasi',
                'Teknologi Informasi dan Jaringan',
                'Keamanan dan Ketertiban',
                'Layanan Akademik dan Administrasi',
            ])
            ->pluck('id', 'name');

        $complaints = [
            [
                'ticket_number' => 'PGD-20260924-0001',
                'category' => 'Sarana dan Prasarana Kampus',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'AC ruang kuliah gedung Fakultas Teknik tidak berfungsi',
                'description' => 'AC di ruang kuliah FT-204 mengeluarkan suara berisik dan tidak lagi mendinginkan ruangan sejak dua minggu terakhir. Kondisi ini mengganggu perkuliahan siang karena ruangan tidak memiliki ventilasi yang cukup.',
                'incident_date' => now()->subDays(18)->toDateString(),
                'incident_location' => 'Ruang FT-204, Gedung Fakultas Teknik',
                'reporter_name' => 'Rina Wulandari',
                'reporter_phone' => '081234567890',
                'reporter_email' => 'rina.wulandari@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0002',
                'category' => 'Kebersihan dan Sanitasi',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => true,
                'subject' => 'Tempat sampah di belakang perpustakaan penuh selama beberapa hari',
                'description' => 'Tempat penampungan sampah di belakang perpustakaan penuh dan belum diangkut sejak akhir pekan. Bau mulai masuk ke area baca dan beberapa sampah berserakan di jalur menuju kantin.',
                'incident_date' => now()->subDays(12)->toDateString(),
                'incident_location' => 'Area belakang Perpustakaan Pusat, dekat jalur menuju kantin',
                'reporter_name' => null,
                'reporter_phone' => null,
                'reporter_email' => null,
                'status' => Complaint::STATUS_BARU,
                'priority' => Complaint::PRIORITY_SEDANG,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0003',
                'category' => 'Teknologi Informasi dan Jaringan',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Wi-Fi kampus tidak dapat digunakan di lantai tiga perpustakaan',
                'description' => 'Jaringan Wi-Fi kampus sering terputus di lantai tiga perpustakaan sejak awal minggu. Perangkat dapat tersambung, tetapi tidak memperoleh akses internet sehingga mahasiswa kesulitan mengakses jurnal untuk tugas akhir.',
                'incident_date' => now()->subDays(9)->toDateString(),
                'incident_location' => 'Lantai tiga Perpustakaan Pusat',
                'reporter_name' => 'Dedi Pratama',
                'reporter_phone' => '082198765432',
                'reporter_email' => 'dedi.pratama@example.test',
                'status' => Complaint::STATUS_SELESAI,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => now()->subDays(3),
            ],
            [
                'ticket_number' => 'PGD-20260924-0004',
                'category' => 'Keamanan dan Ketertiban',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Kendaraan tanpa stiker parkir memenuhi area akses laboratorium',
                'description' => 'Beberapa kendaraan tanpa stiker parkir kampus menggunakan area di depan Laboratorium Terpadu. Kendaraan tersebut menghalangi jalur bongkar muat dan akses kendaraan darurat selama jam praktikum.',
                'incident_date' => now()->subDays(6)->toDateString(),
                'incident_location' => 'Area parkir depan Laboratorium Terpadu',
                'reporter_name' => 'Agus Setiawan',
                'reporter_phone' => '085712345678',
                'reporter_email' => 'agus.setiawan@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_URGENT,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0005',
                'category' => 'Layanan Akademik dan Administrasi',
                'creator_type' => Complaint::CREATOR_EKSTERNAL,
                'is_anonymous' => false,
                'subject' => 'Pengajuan surat keterangan aktif kuliah belum diproses',
                'description' => 'Pengajuan surat keterangan aktif kuliah melalui portal akademik sudah dilakukan dan berkas telah lengkap, tetapi statusnya belum berubah selama delapan hari kerja. Surat tersebut dibutuhkan untuk pengajuan beasiswa dengan batas pengumpulan minggu ini.',
                'incident_date' => now()->subDays(22)->toDateString(),
                'incident_location' => 'Portal Akademik dan loket Biro Administrasi Akademik',
                'reporter_name' => 'Nadia Permatasari',
                'reporter_phone' => '081356789012',
                'reporter_email' => 'nadia.permata@example.test',
                'status' => Complaint::STATUS_DITOLAK,
                'priority' => Complaint::PRIORITY_RENDAH,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0006',
                'category' => 'Sarana dan Prasarana Kampus',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Proyektor ruang seminar sering mati saat digunakan',
                'description' => 'Proyektor di ruang seminar lantai dua sering mati sendiri setelah digunakan sekitar 20 menit. Kegiatan presentasi organisasi mahasiswa harus dipindahkan ke ruangan lain karena kabel dan sumber listrik sudah diperiksa tetapi masalah tetap berulang.',
                'incident_date' => now()->subDays(16)->toDateString(),
                'incident_location' => 'Ruang Seminar 2.05, Gedung Student Center',
                'reporter_name' => 'Fajar Maulana',
                'reporter_phone' => '081298765401',
                'reporter_email' => 'fajar.maulana@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_SEDANG,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0007',
                'category' => 'Kebersihan dan Sanitasi',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => true,
                'subject' => 'Toilet lantai dua gedung perkuliahan mengalami kebocoran',
                'description' => 'Air terus menetes dari sambungan pipa di toilet lantai dua dan membuat lantai licin. Tanda peringatan sudah dipasang oleh petugas, tetapi perbaikan belum dilakukan sehingga berisiko menyebabkan mahasiswa terpeleset.',
                'incident_date' => now()->subDays(5)->toDateString(),
                'incident_location' => 'Toilet lantai dua, Gedung Perkuliahan A',
                'reporter_name' => null,
                'reporter_phone' => null,
                'reporter_email' => null,
                'status' => Complaint::STATUS_BARU,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0008',
                'category' => 'Teknologi Informasi dan Jaringan',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Portal akademik gagal menyimpan perubahan KRS',
                'description' => 'Perubahan mata kuliah pada KRS sudah dipilih sampai tahap konfirmasi, tetapi portal akademik kembali ke halaman awal dan jadwal tidak berubah. Masalah terjadi pada dua perangkat berbeda menjelang batas akhir pengisian KRS.',
                'incident_date' => now()->subDays(8)->toDateString(),
                'incident_location' => 'Portal Akademik, area pengisian KRS semester berjalan',
                'reporter_name' => 'Maya Salsabila',
                'reporter_phone' => '082210987654',
                'reporter_email' => 'maya.salsabila@example.test',
                'status' => Complaint::STATUS_SELESAI,
                'priority' => Complaint::PRIORITY_URGENT,
                'resolved_at' => now()->subDays(4),
            ],
            [
                'ticket_number' => 'PGD-20260924-0009',
                'category' => 'Keamanan dan Ketertiban',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Helm mahasiswa hilang dari area parkir timur',
                'description' => 'Helm yang diletakkan di dalam bagasi motor hilang setelah kendaraan diparkir selama jam kuliah. Kamera di pintu masuk area parkir terlihat mengarah ke lokasi, sehingga mohon rekaman diperiksa dan pengawasan ditingkatkan.',
                'incident_date' => now()->subDays(14)->toDateString(),
                'incident_location' => 'Parkir kendaraan roda dua sisi timur kampus',
                'reporter_name' => 'Bagas Ramadhan',
                'reporter_phone' => '085612340987',
                'reporter_email' => 'bagas.ramadhan@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0010',
                'category' => 'Sarana dan Prasarana Kampus',
                'creator_type' => Complaint::CREATOR_EKSTERNAL,
                'is_anonymous' => false,
                'subject' => 'Akses ramp menuju gedung utama tertutup kendaraan',
                'description' => 'Ramp yang menjadi akses pengguna kursi roda dan pengunjung dengan kebutuhan mobilitas khusus sering digunakan untuk parkir sepeda motor. Kondisi ini menyulitkan akses menuju gedung utama terutama pada jam masuk kuliah.',
                'incident_date' => now()->subDays(3)->toDateString(),
                'incident_location' => 'Ramp akses utama Gedung Rektorat',
                'reporter_name' => 'Siti Nurhayati',
                'reporter_phone' => '081377654320',
                'reporter_email' => 'siti.nurhayati@example.test',
                'status' => Complaint::STATUS_BARU,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0011',
                'category' => 'Kebersihan dan Sanitasi',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Bau tidak sedap berasal dari saluran air kantin',
                'description' => 'Saluran air di belakang kantin menimbulkan bau menyengat sejak saluran pembuangan tersumbat. Bau mengganggu area makan dan semakin kuat setelah hujan, sehingga perlu pembersihan serta pemeriksaan saluran pembuangan.',
                'incident_date' => now()->subDays(11)->toDateString(),
                'incident_location' => 'Belakang kantin mahasiswa, dekat Gedung Student Center',
                'reporter_name' => 'Reza Kurniawan',
                'reporter_phone' => '082134567809',
                'reporter_email' => 'reza.kurniawan@example.test',
                'status' => Complaint::STATUS_SELESAI,
                'priority' => Complaint::PRIORITY_SEDANG,
                'resolved_at' => now()->subDays(2),
            ],
            [
                'ticket_number' => 'PGD-20260924-0012',
                'category' => 'Teknologi Informasi dan Jaringan',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Akun mahasiswa terkunci setelah reset kata sandi',
                'description' => 'Akun mahasiswa terkunci setelah proses reset kata sandi melalui email. Tautan reset sudah digunakan, tetapi sistem tetap menolak login dan menampilkan pesan akun tidak aktif.',
                'incident_date' => now()->subDays(2)->toDateString(),
                'incident_location' => 'Sistem Informasi Akademik dan portal mahasiswa',
                'reporter_name' => 'Kevin Aditya',
                'reporter_phone' => '081245670123',
                'reporter_email' => 'kevin.aditya@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0013',
                'category' => 'Keamanan dan Ketertiban',
                'creator_type' => Complaint::CREATOR_EKSTERNAL,
                'is_anonymous' => true,
                'subject' => 'Pintu gerbang samping terbuka tanpa petugas pada malam hari',
                'description' => 'Pintu gerbang samping masih terbuka setelah kegiatan sore selesai dan tidak terlihat petugas berjaga. Akses tersebut langsung menuju area laboratorium, sehingga berpotensi digunakan oleh orang yang tidak berkepentingan.',
                'incident_date' => now()->subDays(7)->toDateString(),
                'incident_location' => 'Gerbang samping dekat Laboratorium Terpadu',
                'reporter_name' => null,
                'reporter_phone' => null,
                'reporter_email' => null,
                'status' => Complaint::STATUS_BARU,
                'priority' => Complaint::PRIORITY_URGENT,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0014',
                'category' => 'Layanan Akademik dan Administrasi',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Transkrip nilai belum tersedia setelah yudisium',
                'description' => 'Transkrip nilai sementara belum muncul di portal meskipun proses yudisium sudah dinyatakan selesai. Dokumen tersebut dibutuhkan untuk pendaftaran kerja dan batas pengunggahan berkas tinggal tiga hari.',
                'incident_date' => now()->subDays(19)->toDateString(),
                'incident_location' => 'Portal Akademik dan loket Fakultas Ekonomi',
                'reporter_name' => 'Intan Puspitasari',
                'reporter_phone' => '085723456109',
                'reporter_email' => 'intan.puspitasari@example.test',
                'status' => Complaint::STATUS_DIPROSES,
                'priority' => Complaint::PRIORITY_TINGGI,
                'resolved_at' => null,
            ],
            [
                'ticket_number' => 'PGD-20260924-0015',
                'category' => 'Layanan Akademik dan Administrasi',
                'creator_type' => Complaint::CREATOR_INTERNAL,
                'is_anonymous' => false,
                'subject' => 'Pembayaran UKT sudah berhasil tetapi status masih tertunggak',
                'description' => 'Pembayaran UKT melalui kanal bank telah berhasil dan bukti transaksi tersedia, tetapi status pada portal mahasiswa masih tertunggak setelah dua hari kerja. Mohon dilakukan sinkronisasi agar mahasiswa dapat mengakses layanan KRS.',
                'incident_date' => now()->subDays(4)->toDateString(),
                'incident_location' => 'Portal Pembayaran Mahasiswa dan loket keuangan',
                'reporter_name' => 'Andika Saputra',
                'reporter_phone' => '081365432178',
                'reporter_email' => 'andika.saputra@example.test',
                'status' => Complaint::STATUS_DITOLAK,
                'priority' => Complaint::PRIORITY_SEDANG,
                'resolved_at' => null,
            ],
        ];

        foreach ($complaints as $complaint) {
            $categoryId = $categories->get($complaint['category']);
            unset($complaint['category']);

            if ($categoryId === null) {
                continue;
            }

            Complaint::updateOrCreate(
                ['ticket_number' => $complaint['ticket_number']],
                [...$complaint, 'category_id' => $categoryId],
            );
        }
    }
}